import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import SessionProvider from "./components/SessionProvider";
import { AppbarClient } from "./components/AppbarClient";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="w-screen min-h-screen bg-[#ebe6e6]">
          <AppbarClient/>
          {children}
        </div>    
      </body>
      </SessionProvider>
    </html>
  );
}
