name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build The Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name : Generate Prisma Client
        run :  npx prisma genereate --schema=packages/db/prisma/schema.prisma

      - name: Run Build
        run: npm run build
