name: Build and Deploy to Docker Hub

on: 
    push:
        branches:
            - main

jobs:
    Build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Check Out Repo
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.SANTHOSHRAJU06_USERNAME}}
            password: ${{secrets.SANTHOSHRAJU06_PASSWORD}}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./docker/Dockerfile.userApp
            push: true
            tags: santhoshraju06/paytm:latest

    
          
