name: Build and Deploy to Docker Hub

on: 
    push:
        branches:
            - main

jobs:
    Build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Check Out Repo
          uses: actions/checkout@v4

        - name: Log in to Docker Hub 
          env: 
            DOCKER_USERNAME: ${{ secrets.SANTHOSHRAJU06_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.SANTHOSHRAJU06_PASSWORD }} 
          run: | 
            printf '%s' "$DOCKER_TOKEN" | docker login \ --username "$DOCKER_USERNAME" \ --password-stdin

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./docker/Dockerfile.userApp
            push: true
            tags: santhoshraju06/paytm:latest

    
          
